

services:
  web:
    build: .
    container_name: paperrepo_app
    command: gunicorn paperrepo.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: paperrepo_nginx
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/usr/share/nginx/html/static
      - ./media:/app/media
    depends_on:
      - web
